// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_layout from './routes/_layout.tsx'
import * as $api_joke from './routes/api/joke.ts'
import * as $archives_name_ from './routes/archives/[name].tsx'
import * as $archives_index from './routes/archives/index.tsx'
import * as $bookmarks_name_ from './routes/bookmarks/[name].tsx'
import * as $bookmarks_index from './routes/bookmarks/index.tsx'
import * as $categories_name_ from './routes/categories/[name].tsx'
import * as $categories_index from './routes/categories/index.tsx'
import * as $explore_index from './routes/explore/index.tsx'
import * as $helper_index from './routes/helper/index.tsx'
import * as $index from './routes/index.tsx'
import * as $links_index from './routes/links/index.tsx'
import * as $login from './routes/login.tsx'
import * as $tags_name_ from './routes/tags/[name].tsx'
import * as $tags_index from './routes/tags/index.tsx'
import * as $users_index from './routes/users/index.tsx'
import * as $Counter from './islands/Counter.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
    routes: {
        './routes/_404.tsx': $_404,
        './routes/_app.tsx': $_app,
        './routes/_layout.tsx': $_layout,
        './routes/api/joke.ts': $api_joke,
        './routes/archives/[name].tsx': $archives_name_,
        './routes/archives/index.tsx': $archives_index,
        './routes/bookmarks/[name].tsx': $bookmarks_name_,
        './routes/bookmarks/index.tsx': $bookmarks_index,
        './routes/categories/[name].tsx': $categories_name_,
        './routes/categories/index.tsx': $categories_index,
        './routes/explore/index.tsx': $explore_index,
        './routes/helper/index.tsx': $helper_index,
        './routes/index.tsx': $index,
        './routes/links/index.tsx': $links_index,
        './routes/login.tsx': $login,
        './routes/tags/[name].tsx': $tags_name_,
        './routes/tags/index.tsx': $tags_index,
        './routes/users/index.tsx': $users_index,
    },
    islands: {
        './islands/Counter.tsx': $Counter,
    },
    baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
